# Site settings
title: Data Laborer
description: > # this means to ignore newlines until "baseurl:"
  Personnal web site of a data scientist. Statistic, data-visualisation and hacks. R code and soon python.
url: "http://www.data-laborer.eu" # the base hostname & protocol for your site
baseurl: "http://yvescr.github.io"
baseurlknitr: "http://yvescr.github.io"
twitter_username: swiftAmhe
github_username:  yvesCR
permalink: /:year/:month/:title.html
exclude: [blog, _source_no_compile, build.R, knitr-jekyll.Rproj, launch.r, .RData, .Rhistory]

# Build settings
markdown: kramdown
